version: '3.4'

services:
  httpclientcognitive:
    image: ${DOCKER_REGISTRY-}httpclientcognitive
    build:
      context: .
      dockerfile: HttpClientCognitive/Dockerfile
  language.api:
    image: mcr.microsoft.com/azure-cognitive-services/language
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - Eula=accept
      - Billing=https://westeurope.api.cognitive.microsoft.com/text/analytics/v2.0
      - ApiKey=58f0e5f3866846c49e5c27e3682045d8