version: '3.4'

services:
  armwebapp:
    image: registrydemosession.azurecr.io/armwebapp
    build:
      context: .
      dockerfile: ARMWebApp/Dockerfile
    depends_on:
      - simpsonvision.api
  simpsonvision.api:
    image: registrydemosession.azurecr.io/simpsonvision.api
    build:
      context: './SimpsonCustomVision.DockerFile.Linux'
      dockerfile: Dockerfile
    expose:
      - "80"
    ports:
      - "8081:80"
