version: '3.4'

services:
  cognitiveapp:
    image: registrydemosession.azurecr.io/cognitiveapp
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - sentiment.api
      - language.api
      - customvision.api
  customvision.api:
    image: registrydemosession.azurecr.io/customvision.api
    expose:
      - "80"
    ports:
      - "8081:80"
  sentiment.api:
    image: mcr.microsoft.com/azure-cognitive-services/sentiment
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - Eula=accept
      - Billing=https://westeurope.api.cognitive.microsoft.com/text/analytics/v2.0
      - ApiKey=bf74a8f377f645a295f983ec0f22ce2d
  language.api:
    image: mcr.microsoft.com/azure-cognitive-services/language
    expose:
      - "5000"
    ports:
      - "5001:5000"
    environment:
      - Eula=accept
      - Billing=https://westeurope.api.cognitive.microsoft.com/text/analytics/v2.0
      - ApiKey=bf74a8f377f645a295f983ec0f22ce2d